name: Run Python Script on Windows

on:
  # Manual trigger
  workflow_dispatch:

jobs:
  run-python-script:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Specify the Python version

      # Step 3: Install dependencies (if required)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        shell: cmd

      # Step 3: Create C:\test directory if it doesn't exist
      - name: Create C:\test directory
        run: |
          mkdir C:\test

      # Step 4: Copy test.py from build folder to C:\test
      - name: Copy test.py to C:\test
        run: |
          copy mybuild\test.py C:\test\test.py

      # Step 5: Run test.py from C:\test directory
      - name: Run test.py
        run: |
          cd C:\test
          python test.py
        shell: cmd
